### ISSUE TITLE
Cannot zoom in on small font

### ISSUE THREAD

**Issue by ward** [mwenge/dirtylittlesql.com#6]
Hello, the font is too small on my screen. You seem to have defined `font-size` using `vw` as unit, so I cannot use the standard browser zoom in to make it readable (tested in firefox). I do not have much experience with this, but [MDN seems to have a solution](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Responsive_Design#using_viewport_units_for_responsive_typography).

**Comment by mwenge** [comment]
Thanks - sounds like a good idea!
